# .symfony.local.yaml
workers:
#   built-in command that starts messenger consumer
  messenger_consume_obj:
       cmd: ['symfony', 'console', 'messenger:consume', 'target.translate' ]
       watch: ['config', 'src', 'templates', 'vendor']


