<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260530100218 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE babel_term (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, path VARCHAR(512) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, sort INT DEFAULT NULL, term_set_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_77FE42F2F3AD3475 ON babel_term (term_set_id)');
        $this->addSql('CREATE INDEX IDX_77FE42F2727ACA70 ON babel_term (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_code_uq ON babel_term (term_set_id, code)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_path_uq ON babel_term (term_set_id, path)');
        $this->addSql('CREATE TABLE str_tr (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, str_code VARCHAR(64) NOT NULL, target_locale VARCHAR(10) NOT NULL, engine VARCHAR(20) DEFAULT NULL, text TEXT DEFAULT NULL, status VARCHAR(16) DEFAULT \'new\' NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_tr_target_locale_idx ON str_tr (target_locale)');
        $this->addSql('CREATE INDEX str_tr_str_code_idx ON str_tr (str_code)');
        $this->addSql('CREATE UNIQUE INDEX str_tr_uq ON str_tr (str_code, target_locale, engine)');
        $this->addSql('CREATE TABLE term_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX term_set_code_uq ON term_set (code)');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2F3AD3475 FOREIGN KEY (term_set_id) REFERENCES term_set (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2727ACA70 FOREIGN KEY (parent_id) REFERENCES babel_term (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tr DROP CONSTRAINT fk_b481be1d538ff456');
        $this->addSql('DROP TABLE tr');
        $this->addSql('ALTER TABLE str DROP CONSTRAINT str_pkey');
        $this->addSql('ALTER TABLE str ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE str ADD source_locale VARCHAR(10) NOT NULL');
        $this->addSql('ALTER TABLE str DROP src_locale');
        $this->addSql('ALTER TABLE str DROP created_at');
        $this->addSql('ALTER TABLE str DROP updated_at');
        $this->addSql('ALTER TABLE str DROP status');
        $this->addSql('ALTER TABLE str DROP locale_statuses');
        $this->addSql('ALTER TABLE str DROP marking');
        $this->addSql('ALTER TABLE str ALTER context TYPE VARCHAR(80)');
        $this->addSql('ALTER TABLE str ALTER meta SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE str ALTER meta SET NOT NULL');
        $this->addSql('ALTER TABLE str RENAME COLUMN hash TO code');
        $this->addSql('ALTER TABLE str RENAME COLUMN original TO source');
        $this->addSql('CREATE INDEX str_ctx_idx ON str (context)');
        $this->addSql('CREATE INDEX str_src_locale_idx ON str (source_locale)');
        $this->addSql('CREATE INDEX str_src_locale_ctx_idx ON str (source_locale, context)');
        $this->addSql('CREATE UNIQUE INDEX str_code_uq ON str (code)');
        $this->addSql('ALTER TABLE str ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE target ADD pending_steps JSON DEFAULT \'{}\' NOT NULL');
        $this->addSql('DROP INDEX idx_75ea56e0e3bd61ce');
        $this->addSql('DROP INDEX idx_75ea56e016ba31db');
        $this->addSql('DROP INDEX idx_75ea56e0fb7336f0');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA toolkit_experimental');
        $this->addSql('CREATE SCHEMA timescaledb_information');
        $this->addSql('CREATE SCHEMA timescaledb_experimental');
        $this->addSql('CREATE SCHEMA _timescaledb_internal');
        $this->addSql('CREATE SCHEMA _timescaledb_functions');
        $this->addSql('CREATE SCHEMA _timescaledb_config');
        $this->addSql('CREATE SCHEMA _timescaledb_catalog');
        $this->addSql('CREATE SCHEMA _timescaledb_cache');
        $this->addSql('CREATE TABLE tr (meta JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) DEFAULT NULL, hash VARCHAR(40) NOT NULL, str_hash VARCHAR(32) NOT NULL, locale VARCHAR(8) NOT NULL, text TEXT DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (hash))');
        $this->addSql('CREATE INDEX idx_b481be1d538ff456 ON tr (str_hash)');
        $this->addSql('ALTER TABLE tr ADD CONSTRAINT fk_b481be1d538ff456 FOREIGN KEY (str_hash) REFERENCES str (hash) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2F3AD3475');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2727ACA70');
        $this->addSql('DROP TABLE babel_term');
        $this->addSql('DROP TABLE str_tr');
        $this->addSql('DROP TABLE term_set');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('ALTER TABLE str DROP CONSTRAINT str_pkey');
        $this->addSql('DROP INDEX str_ctx_idx');
        $this->addSql('DROP INDEX str_src_locale_idx');
        $this->addSql('DROP INDEX str_src_locale_ctx_idx');
        $this->addSql('DROP INDEX str_code_uq');
        $this->addSql('ALTER TABLE str ADD src_locale VARCHAR(8) NOT NULL');
        $this->addSql('ALTER TABLE str ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE str ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE str ADD status VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE str ADD locale_statuses JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE str ADD marking VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE str DROP id');
        $this->addSql('ALTER TABLE str DROP source_locale');
        $this->addSql('ALTER TABLE str ALTER context TYPE VARCHAR(128)');
        $this->addSql('ALTER TABLE str ALTER meta DROP DEFAULT');
        $this->addSql('ALTER TABLE str ALTER meta DROP NOT NULL');
        $this->addSql('ALTER TABLE str RENAME COLUMN code TO hash');
        $this->addSql('ALTER TABLE str RENAME COLUMN source TO original');
        $this->addSql('ALTER TABLE str ADD PRIMARY KEY (hash)');
        $this->addSql('ALTER TABLE target DROP pending_steps');
    }
}
